// Code generated by naatre-swift-sdk-generator; DO NOT EDIT.

import Foundation
import NaatreCore

public let swiftGeneratorVersion = "naatre.generator.swift-sdk-1"

public struct Account: Codable, Sendable {
    public var status: Status?
    public var balance: Money?
    public var displayName: String?
}

public typealias Money = NaatreDecimal

public enum Status: Codable, Hashable, Sendable {
    case active
    case pending
    case unknown(String)

    public init(from decoder: Decoder) throws {
        let value = try decoder.singleValueContainer().decode(String.self)
        switch value {
        case "ACTIVE": self = .active
        case "PENDING": self = .pending
        default: self = .unknown(value)
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .active: try container.encode("ACTIVE")
        case .pending: try container.encode("PENDING")
        case let .unknown(value): try container.encode(value)
        }
    }
}

public struct GetAccountVariables: Codable, Sendable {
    public let id: String
    public let nickname: Input<String>
    public let tags: Input<[String]>
    public let filter: Input<[String: String]>

    public init(id: String, nickname: Input<String> = .missing, tags: Input<[String]> = .missing, filter: Input<[String: String]> = .missing) {
        self.id = id
        self.nickname = nickname
        self.tags = tags
        self.filter = filter
    }

    enum CodingKeys: String, CodingKey {
        case id = "id"
        case nickname = "nickname"
        case tags = "tags"
        case filter = "filter"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(String.self, forKey: .id)
        nickname = try Input<String>.decode(from: container, forKey: .nickname, allowNull: true)
        tags = try Input<[String]>.decode(from: container, forKey: .tags, allowNull: true)
        filter = try Input<[String: String]>.decode(from: container, forKey: .filter, allowNull: true)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        switch nickname {
        case .missing: break
        case .null: try container.encodeNil(forKey: .nickname)
        case let .value(value): try container.encode(value, forKey: .nickname)
        }
        switch tags {
        case .missing: break
        case .null: try container.encodeNil(forKey: .tags)
        case let .value(value): try container.encode(value, forKey: .tags)
        }
        switch filter {
        case .missing: break
        case .null: try container.encodeNil(forKey: .filter)
        case let .value(value): try container.encode(value, forKey: .filter)
        }
    }
}

public struct GetAccountResult: Codable, Sendable {
    public let profile: Selected<GetAccountResultProfile>
    public let later: Selected<String>

    enum CodingKeys: String, CodingKey {
        case profile = "profile"
        case later = "later"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        profile = try Selected.decode(from: container, forKey: .profile, pendingWhenMissing: false)
        later = try Selected.decode(from: container, forKey: .later, pendingWhenMissing: true)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try profile.encode(to: &container, forKey: .profile)
        try later.encode(to: &container, forKey: .later)
    }
}

public struct GetAccountResultProfile: Codable, Sendable {
    public let display: Selected<String>
    public let nickname: Selected<String>

    enum CodingKeys: String, CodingKey {
        case display = "display"
        case nickname = "nickname"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        display = try Selected.decode(from: container, forKey: .display, pendingWhenMissing: false)
        nickname = try Selected.decode(from: container, forKey: .nickname, pendingWhenMissing: false)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try display.encode(to: &container, forKey: .display)
        try nickname.encode(to: &container, forKey: .nickname)
    }
}

public func makeGetAccount(_ variables: GetAccountVariables) throws -> NaatreCore.Operation<GetAccountVariables, GetAccountResult> {
    let persisted = try PersistedReference(digest: "cc863005080edcb85ec0345a50593dc58111896bbbe7ff86475ef2412fc5cb90")
    return try NaatreCore.Operation(name: "GetAccount", kind: .query, persisted: persisted, variables: variables)
}

public func swiftManifest() throws -> Manifest {
    try Manifest(operations: [ManifestOperation(name: "GetAccount", kind: .query, persisted: try PersistedReference(digest: "cc863005080edcb85ec0345a50593dc58111896bbbe7ff86475ef2412fc5cb90"))])
}
