from __future__ import annotations

import sys
from collections.abc import Mapping, Sequence
from pathlib import Path

from .json import JSONValue, strict_json_loads
from .sdkgen import (
    _array as _sequence,
)
from .sdkgen import (
    _identifier,
    _python_name,
    _string,
)
from .sdkgen import (
    _object as _mapping,
)
from .sdkgen import (
    _python_type as _client_python_type,
)

SERVER_GENERATOR_VERSION = "naatre.generator.python-worker-1"
_MAXIMUM_INPUT_BYTES = 16 << 20


def generate_server(model_bytes: bytes) -> bytes:
    if not model_bytes or len(model_bytes) > _MAXIMUM_INPUT_BYTES:
        raise ValueError("PYTHON_WORKER_GENERATOR_INPUT_LIMIT")
    model = _mapping(strict_json_loads(model_bytes, maximum_bytes=_MAXIMUM_INPUT_BYTES))
    if model.get("version") != "naatre.generator-model-1":
        raise ValueError("PYTHON_WORKER_GENERATOR_INVALID_MODEL")
    operations = [_mapping(value) for value in _sequence(model.get("operations"))]
    lines = [
        "# Code generated by the Naatre Python worker generator; DO NOT EDIT.",
        "from __future__ import annotations",
        "",
        "from collections.abc import Awaitable",
        "from dataclasses import dataclass",
        "from decimal import Decimal",
        "from typing import Protocol",
        "",
        "from naatre import MISSING, MissingType, Timestamp",
        "from naatre.worker import (",
        "    DataclassCodec, Field, HandlerRequest, ListCodec, MapCodec, NullableCodec,",
        "    Registry, ScalarCodec,",
        ")",
        "",
        "from .operations import (",
    ]
    for operation in sorted(operations, key=lambda item: _string(item.get("name"))):
        lines.append(f"    {_identifier(operation.get('name'))}Variables,")
    lines.extend([")", "", f"SERVER_GENERATOR_VERSION = {SERVER_GENERATOR_VERSION!r}", ""])
    for operation in sorted(operations, key=lambda item: _string(item.get("name"))):
        lines.extend(_render_operation(operation))
        lines.append("")
    return ("\n".join(lines).rstrip() + "\n").encode()


def _render_operation(operation: Mapping[str, JSONValue]) -> list[str]:
    symbol = _identifier(operation.get("name"))
    lower = _python_name(symbol)
    variables = [_mapping(value) for value in _sequence(operation.get("variables"))]
    result = _mapping(operation.get("result"))
    result_fields = [_mapping(value) for value in _sequence(result.get("fields"))]
    lines: list[str] = []

    nested_classes: list[tuple[str, Sequence[Mapping[str, JSONValue]]]] = []
    for result_field in result_fields:
        node = _mapping(result_field.get("result"))
        if node.get("kind") == "object":
            nested_classes.append(
                (
                    f"{symbol}Server{_identifier(_string(result_field.get('name')).title())}",
                    [_mapping(value) for value in _sequence(node.get("fields"))],
                )
            )
    for class_name, class_fields in nested_classes:
        lines.extend(_render_output_model(class_name, class_fields))
        lines.append("")

    result_name = f"{symbol}ServerResult"
    lines.extend(["@dataclass(frozen=True, slots=True)", f"class {result_name}:"])
    if not result_fields:
        lines.append("    pass")
    object_field_names = (
        _string(field.get("name"))
        for field in result_fields
        if _mapping(field.get("result")).get("kind") == "object"
    )
    nested_names = {
        field_name: class_name
        for class_name, field_name in zip(
            (name for name, _fields in nested_classes), object_field_names, strict=True
        )
    }
    for field in result_fields:
        node = _mapping(field.get("result"))
        wire_name = _string(field.get("name"))
        annotation = nested_names.get(wire_name, _python_type(_string(node.get("type"))))
        if node.get("nullable") is True:
            annotation += " | None"
        if field.get("presence") not in {"required"}:
            annotation += " | MissingType = MISSING"
        lines.append(f"    {_python_name(wire_name)}: {annotation}")

    lines.extend(
        [
            "",
            f"class {symbol}SyncHandler(Protocol):",
            "    def __call__(",
            f"        self, request: HandlerRequest[{symbol}Variables]",
            f"    ) -> {result_name}: ...",
            "",
            f"class {symbol}AsyncHandler(Protocol):",
            "    def __call__(",
            f"        self, request: HandlerRequest[{symbol}Variables]",
            f"    ) -> Awaitable[{result_name}]: ...",
            "",
            f"{lower.upper()}_INPUT_CODEC = DataclassCodec(",
            f"    {symbol}Variables,",
            "    (",
        ]
    )
    lines.extend(f"        {_field_codec(field)}," for field in variables)
    lines.extend(
        [
            "    ),",
            ")",
            "",
            f"{lower.upper()}_OUTPUT_CODEC = DataclassCodec(",
            f"    {result_name},",
            "    (",
        ]
    )
    for field in result_fields:
        node = _mapping(field.get("result"))
        name = _string(field.get("name"))
        if node.get("kind") == "object":
            class_name = nested_names[name]
            nested_fields = [_mapping(value) for value in _sequence(node.get("fields"))]
            codec = _dataclass_codec(class_name, nested_fields)
        else:
            codec = _codec_expression(_string(node.get("type")), node.get("nullable") is True)
        required = field.get("presence") == "required"
        lines.append(
            f"        Field({name!r}, {codec}, attribute={_python_name(name)!r}, "
            f"required={required!r}),"
        )
    lines.extend(
        [
            "    ),",
            ")",
            "",
            f"def bind_{lower}_sync(",
            f"    registry: Registry, handler_id: str, handler: {symbol}SyncHandler",
            ") -> None:",
            "    registry.bind_sync(",
            f"        handler_id, {lower.upper()}_INPUT_CODEC, "
            f"{lower.upper()}_OUTPUT_CODEC, handler,",
            f"        effect={_operation_kind(operation)!r},",
            "    )",
            "",
            f"def bind_{lower}_async(",
            f"    registry: Registry, handler_id: str, handler: {symbol}AsyncHandler",
            ") -> None:",
            "    registry.bind_async(",
            f"        handler_id, {lower.upper()}_INPUT_CODEC, "
            f"{lower.upper()}_OUTPUT_CODEC, handler,",
            f"        effect={_operation_kind(operation)!r},",
            "    )",
        ]
    )
    return lines


def _render_output_model(
    class_name: str, fields: Sequence[Mapping[str, JSONValue]]
) -> list[str]:
    lines = ["@dataclass(frozen=True, slots=True)", f"class {class_name}:"]
    if not fields:
        lines.append("    pass")
    for field in fields:
        node = _mapping(field.get("result"))
        annotation = _python_type(_string(node.get("type")))
        if node.get("nullable") is True:
            annotation += " | None"
        if field.get("presence") != "required":
            annotation += " | MissingType = MISSING"
        lines.append(f"    {_python_name(_string(field.get('name')))}: {annotation}")
    return lines


def _field_codec(field: Mapping[str, JSONValue]) -> str:
    name = _string(field.get("name"))
    codec = _codec_expression(_string(field.get("type")), field.get("nullable") is True)
    return (
        f"Field({name!r}, {codec}, attribute={_python_name(name)!r}, "
        f"required={field.get('required') is True!r})"
    )


def _dataclass_codec(class_name: str, fields: Sequence[Mapping[str, JSONValue]]) -> str:
    entries = ", ".join(_field_codec_from_result(field) for field in fields)
    if len(fields) == 1:
        entries += ","
    return f"DataclassCodec({class_name}, ({entries}))"


def _field_codec_from_result(field: Mapping[str, JSONValue]) -> str:
    name = _string(field.get("name"))
    node = _mapping(field.get("result"))
    codec = _codec_expression(_string(node.get("type")), node.get("nullable") is True)
    return (
        f"Field({name!r}, {codec}, "
        f"attribute={_python_name(name)!r}, required={field.get('presence') == 'required'!r})"
    )


def _codec_expression(type_name: str, nullable: bool) -> str:
    if type_name == "StringList":
        expression = "ListCodec(ScalarCodec('String'))"
    elif type_name == "StringMap":
        expression = "MapCodec(ScalarCodec('String'))"
    elif type_name == "Money":
        expression = "ScalarCodec('Decimal')"
    else:
        expression = f"ScalarCodec({type_name!r})"
    return f"NullableCodec({expression})" if nullable else expression


def _operation_kind(operation: Mapping[str, JSONValue]) -> str:
    document = _mapping(operation.get("document"))
    operations = [_mapping(value) for value in _sequence(document.get("operations"))]
    if len(operations) != 1:
        raise ValueError("PYTHON_WORKER_GENERATOR_INVALID_MODEL")
    kind = _string(operations[0].get("kind"))
    if kind not in {"query", "mutation", "subscription"}:
        raise ValueError("PYTHON_WORKER_GENERATOR_INVALID_MODEL")
    return kind


def _python_type(value: str) -> str:
    return "Timestamp" if value == "Timestamp" else _client_python_type(value)


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: python -m naatre.servergen MODEL OUTPUT")
    source = generate_server(Path(sys.argv[1]).read_bytes())
    Path(sys.argv[2]).write_bytes(source)


if __name__ == "__main__":
    main()
