// Package doccheck supplies deterministic checks for the published v1 guides.
package doccheck

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var publicCode = regexp.MustCompile(`^[A-Z][A-Z0-9_]*$`)
var quotedPublicCode = regexp.MustCompile("[\\\"'`]([A-Z][A-Z0-9_]*_[A-Z0-9_]+)[\\\"'`]")

// PublicCodes returns stable public codes named by code-bearing fields in the
// executable v1 fixtures. The fixtures, rather than prose, own this inventory.
func PublicCodes(root string) ([]string, error) {
	files, err := filepath.Glob(filepath.Join(root, "conformance", "v1", "*.json"))
	if err != nil {
		return nil, err
	}
	codes := make(map[string]struct{})
	for _, path := range files {
		content, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		var value any
		if err := json.Unmarshal(content, &value); err != nil {
			return nil, fmt.Errorf("decode %s: %w", path, err)
		}
		collectCodes(value, false, codes)
	}
	if err := collectSourceCodes(root, codes); err != nil {
		return nil, err
	}
	result := make([]string, 0, len(codes))
	for code := range codes {
		result = append(result, code)
	}
	sort.Strings(result)
	return result, nil
}

func collectSourceCodes(root string, codes map[string]struct{}) error {
	extensions := map[string]bool{
		".cs": true, ".dart": true, ".go": true, ".java": true, ".js": true,
		".kt": true, ".mjs": true, ".php": true, ".py": true, ".rb": true,
		".rs": true, ".swift": true, ".ts": true,
	}
	return filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if entry.Name() == ".git" || entry.Name() == "node_modules" || entry.Name() == "target" {
				return filepath.SkipDir
			}
			return nil
		}
		if !extensions[filepath.Ext(path)] {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		for _, match := range quotedPublicCode.FindAllSubmatch(content, -1) {
			codes[string(match[1])] = struct{}{}
		}
		return nil
	})
}

func collectCodes(value any, codeContext bool, codes map[string]struct{}) {
	switch typed := value.(type) {
	case map[string]any:
		for key, child := range typed {
			keyContext := strings.Contains(strings.ToLower(key), "code")
			if codeContext && publicCode.MatchString(key) {
				codes[key] = struct{}{}
			}
			collectCodes(child, keyContext, codes)
		}
	case []any:
		for _, child := range typed {
			collectCodes(child, codeContext, codes)
		}
	case string:
		if codeContext && publicCode.MatchString(typed) {
			codes[typed] = struct{}{}
		}
	}
}

// RenderErrorIndex creates the generated, clickable error-code index.
func RenderErrorIndex(codes []string) []byte {
	var result strings.Builder
	result.WriteString("# Public error-code index\n\n")
	result.WriteString("This file is generated from code-bearing fields in `conformance/v1/*.json` and quoted stable code constants in implementation sources. ")
	result.WriteString("Each code links to the common diagnostic workflow; fixture and clause links in the response identify the specific contract.\n\n")
	result.WriteString("Do not edit this file directly. Run `go generate ./internal/doccheck`.\n\n")
	for _, code := range codes {
		fmt.Fprintf(&result, "- [`%s`](troubleshooting.md#diagnostic-workflow)\n", code)
	}
	return []byte(result.String())
}
